# version: '3'
services:
  ts-n8n:
    image: tailscale/tailscale:latest
    container_name: ts-n8n
    hostname: n8n
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/n8n.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./config:/config
      - /opt/ts-n8n/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  initContainer:
    image: busybox
    command: ["sh", "-c", "chown -R 1000:1000 /home/node/.n8n"]
    volumes:
      - /opt/n8n_data:/home/node/.n8n

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
    volumes:
      - /opt/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 30s
      timeout: 10s
      retries: 3

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.121.2
    restart: always
    container_name: n8n
    network_mode: service:ts-n8n
    depends_on:
      - initContainer
      - postgres
      - ts-n8n
    volumes:
      - /opt/n8n_data:/home/node/.n8n
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.dzo-byzantine.ts.net
      - N8N_PROXY_HOPS=1
      # - N8N_SECURE_COOKIE=false
      # Database configuration
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      # Vector store configuration
      - N8N_VECTOR_STORE_ENABLED=true
      - N8N_VECTOR_STORE_TYPE=postgres
      - N8N_VECTOR_STORE_POSTGRES_HOST=postgres
      - N8N_VECTOR_STORE_POSTGRES_PORT=5432
      - N8N_VECTOR_STORE_POSTGRES_DATABASE=n8n
      - N8N_VECTOR_STORE_POSTGRES_USER=n8n
